{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 92,
   "id": "8336a13e-91f7-4c92-b4a8-1949fd0286f0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import train_test_split, cross_val_score\n",
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense\n",
    "from tensorflow.keras.layers import Dropout\n",
    "from tensorflow.keras.callbacks import EarlyStopping\n",
    "from keras.wrappers.scikit_learn import KerasClassifier\n",
    "from sklearn.model_selection import KFold"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "id": "d76d31e8-9105-4e10-9c70-6e82cc1a8e7a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>vegetable</th>\n",
       "      <th>flavor_family</th>\n",
       "      <th>texture</th>\n",
       "      <th>prepared</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>artichokes</td>\n",
       "      <td>mild/neutral</td>\n",
       "      <td>soft-chewy</td>\n",
       "      <td>roast</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>artichokes</td>\n",
       "      <td>mild/neutral</td>\n",
       "      <td>soft-chewy</td>\n",
       "      <td>steam</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>arugula</td>\n",
       "      <td>spicy</td>\n",
       "      <td>soft-chewy</td>\n",
       "      <td>salad</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>arugula</td>\n",
       "      <td>spicy</td>\n",
       "      <td>soft-chewy</td>\n",
       "      <td>salad</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>asparagus</td>\n",
       "      <td>grassy</td>\n",
       "      <td>crunchy</td>\n",
       "      <td>salad</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    vegetable flavor_family     texture prepared\n",
       "0  artichokes  mild/neutral  soft-chewy    roast\n",
       "1  artichokes  mild/neutral  soft-chewy    steam\n",
       "2     arugula         spicy  soft-chewy    salad\n",
       "3     arugula         spicy  soft-chewy    salad\n",
       "4   asparagus        grassy     crunchy    salad"
      ]
     },
     "execution_count": 64,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.read_csv('./data/veg_model_data.csv')\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "id": "ef7af1c7-db71-4962-a497-acbe574a8835",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_dummy = pd.get_dummies(df, columns=df.columns[1:], drop_first=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "id": "422b1976-ec50-4a66-852a-9b4a98cfebeb",
   "metadata": {},
   "outputs": [],
   "source": [
    "X = df.drop(columns='vegetable')\n",
    "y = df['vegetable']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "id": "97f5d65d-eb72-4f04-ab7f-7c213c9996cf",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "id": "90ae52aa-5210-4420-919a-e8ec456df6c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# rfc = RandomForestClassifier()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "id": "83a9d08c-625d-46d4-b235-b95ffc9f9659",
   "metadata": {},
   "outputs": [],
   "source": [
    "# knn = KNeighborsClassifier()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6f46ee0b-e2af-41ec-8fa2-0f98a906c582",
   "metadata": {},
   "outputs": [],
   "source": [
    "# cross_val_score(knn, X_train, y_train).mean()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6e2b2e3a-1bf4-4c7e-8cbf-94371e0cb50b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "id": "4dea4adb-9cfd-4f4c-ad85-21234f9ffc33",
   "metadata": {},
   "outputs": [],
   "source": [
    "import category_encoders as ce"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "408044b1-9dc9-4dfd-afcc-558adc0c4ed6",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\category_encoders\\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead\n",
      "  elif pd.api.types.is_categorical(cols):\n"
     ]
    }
   ],
   "source": [
    "encoder = ce.OneHotEncoder(cols=df.columns[1:])\n",
    "df_enc = encoder.fit_transform(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "id": "a5b8218c-85e8-4d63-a01d-0a7e09f31ae4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>vegetable</th>\n",
       "      <th>flavor_family_1</th>\n",
       "      <th>flavor_family_2</th>\n",
       "      <th>flavor_family_3</th>\n",
       "      <th>flavor_family_4</th>\n",
       "      <th>flavor_family_5</th>\n",
       "      <th>texture_1</th>\n",
       "      <th>texture_2</th>\n",
       "      <th>texture_3</th>\n",
       "      <th>texture_4</th>\n",
       "      <th>texture_5</th>\n",
       "      <th>prepared_1</th>\n",
       "      <th>prepared_2</th>\n",
       "      <th>prepared_3</th>\n",
       "      <th>prepared_4</th>\n",
       "      <th>prepared_5</th>\n",
       "      <th>prepared_6</th>\n",
       "      <th>prepared_7</th>\n",
       "      <th>prepared_8</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>artichokes</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>artichokes</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>arugula</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>arugula</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>asparagus</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>83</th>\n",
       "      <td>turnips</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>84</th>\n",
       "      <td>garlic</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85</th>\n",
       "      <td>garlic</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>86</th>\n",
       "      <td>lettuce</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>87</th>\n",
       "      <td>lettuce</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>88 rows × 19 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     vegetable  flavor_family_1  flavor_family_2  flavor_family_3  \\\n",
       "0   artichokes                1                0                0   \n",
       "1   artichokes                1                0                0   \n",
       "2      arugula                0                1                0   \n",
       "3      arugula                0                1                0   \n",
       "4    asparagus                0                0                1   \n",
       "..         ...              ...              ...              ...   \n",
       "83     turnips                0                1                0   \n",
       "84      garlic                0                1                0   \n",
       "85      garlic                0                1                0   \n",
       "86     lettuce                1                0                0   \n",
       "87     lettuce                1                0                0   \n",
       "\n",
       "    flavor_family_4  flavor_family_5  texture_1  texture_2  texture_3  \\\n",
       "0                 0                0          1          0          0   \n",
       "1                 0                0          1          0          0   \n",
       "2                 0                0          1          0          0   \n",
       "3                 0                0          1          0          0   \n",
       "4                 0                0          0          1          0   \n",
       "..              ...              ...        ...        ...        ...   \n",
       "83                0                0          0          0          1   \n",
       "84                0                0          1          0          0   \n",
       "85                0                0          1          0          0   \n",
       "86                0                0          0          0          1   \n",
       "87                0                0          0          0          1   \n",
       "\n",
       "    texture_4  texture_5  prepared_1  prepared_2  prepared_3  prepared_4  \\\n",
       "0           0          0           1           0           0           0   \n",
       "1           0          0           0           1           0           0   \n",
       "2           0          0           0           0           1           0   \n",
       "3           0          0           0           0           1           0   \n",
       "4           0          0           0           0           1           0   \n",
       "..        ...        ...         ...         ...         ...         ...   \n",
       "83          0          0           0           0           0           0   \n",
       "84          0          0           1           0           0           0   \n",
       "85          0          0           0           0           0           1   \n",
       "86          0          0           0           0           1           0   \n",
       "87          0          0           0           0           1           0   \n",
       "\n",
       "    prepared_5  prepared_6  prepared_7  prepared_8  \n",
       "0            0           0           0           0  \n",
       "1            0           0           0           0  \n",
       "2            0           0           0           0  \n",
       "3            0           0           0           0  \n",
       "4            0           0           0           0  \n",
       "..         ...         ...         ...         ...  \n",
       "83           0           0           0           1  \n",
       "84           0           0           0           0  \n",
       "85           0           0           0           0  \n",
       "86           0           0           0           0  \n",
       "87           0           0           0           0  \n",
       "\n",
       "[88 rows x 19 columns]"
      ]
     },
     "execution_count": 75,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_enc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "id": "51b1af84-1e88-45cc-97da-de6b64e08ade",
   "metadata": {},
   "outputs": [],
   "source": [
    "X = df_enc.drop(columns='vegetable').astype(float)\n",
    "y = df_enc['vegetable']\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "id": "c362557d-0813-40c9-a74b-122979e4b4e8",
   "metadata": {},
   "outputs": [],
   "source": [
    "tf.random.set_seed(42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "id": "10457287-56a3-4579-8e75-dd2f685f5a96",
   "metadata": {},
   "outputs": [],
   "source": [
    "n_input = X_train.shape[1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "id": "7e0d5ee6-0c54-4339-91a3-e0fe1e723d01",
   "metadata": {},
   "outputs": [],
   "source": [
    "model = Sequential()\n",
    "model.add(Dense(15, input_shape=(n_input,), activation='relu'))\n",
    "model.add(Dense(10, activation='relu'))\n",
    "model.add(Dense(1, activation='softmax'))\n",
    "\n",
    "model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])\n",
    "\n",
    "early_stop = EarlyStopping(monitor='val_loss', patience=3, verbose=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "id": "f6b534fd-54ba-4aee-8dfa-0b7a33288277",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "ename": "UnimplementedError",
     "evalue": " Cast string to float is not supported\n\t [[node categorical_crossentropy/Cast (defined at <ipython-input-87-a716fff89f9e>:1) ]] [Op:__inference_train_function_2954]\n\nFunction call stack:\ntrain_function\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mUnimplementedError\u001b[0m                        Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-87-a716fff89f9e>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mhistory\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mmodel\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX_train\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_train\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalidation_data\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX_test\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_test\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mepochs\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m20\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mcallbacks\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mearly_stop\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m~\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py\u001b[0m in \u001b[0;36mfit\u001b[1;34m(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)\u001b[0m\n\u001b[0;32m   1182\u001b[0m                 _r=1):\n\u001b[0;32m   1183\u001b[0m               \u001b[0mcallbacks\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mon_train_batch_begin\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mstep\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1184\u001b[1;33m               \u001b[0mtmp_logs\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtrain_function\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0miterator\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1185\u001b[0m               \u001b[1;32mif\u001b[0m \u001b[0mdata_handler\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshould_sync\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1186\u001b[0m                 \u001b[0mcontext\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0masync_wait\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\u001b[0m in \u001b[0;36m__call__\u001b[1;34m(self, *args, **kwds)\u001b[0m\n\u001b[0;32m    883\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    884\u001b[0m       \u001b[1;32mwith\u001b[0m \u001b[0mOptionalXlaContext\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_jit_compile\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 885\u001b[1;33m         \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_call\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwds\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    886\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    887\u001b[0m       \u001b[0mnew_tracing_count\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexperimental_get_tracing_count\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\u001b[0m in \u001b[0;36m_call\u001b[1;34m(self, *args, **kwds)\u001b[0m\n\u001b[0;32m    948\u001b[0m         \u001b[1;31m# Lifting succeeded, so variables are initialized and we can run the\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    949\u001b[0m         \u001b[1;31m# stateless function.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 950\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_stateless_fn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwds\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    951\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    952\u001b[0m       \u001b[0m_\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0m_\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0m_\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfiltered_flat_args\u001b[0m \u001b[1;33m=\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m\\\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\u001b[0m in \u001b[0;36m__call__\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m   3037\u001b[0m       (graph_function,\n\u001b[0;32m   3038\u001b[0m        filtered_flat_args) = self._maybe_define_function(args, kwargs)\n\u001b[1;32m-> 3039\u001b[1;33m     return graph_function._call_flat(\n\u001b[0m\u001b[0;32m   3040\u001b[0m         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access\n\u001b[0;32m   3041\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\u001b[0m in \u001b[0;36m_call_flat\u001b[1;34m(self, args, captured_inputs, cancellation_manager)\u001b[0m\n\u001b[0;32m   1961\u001b[0m         and executing_eagerly):\n\u001b[0;32m   1962\u001b[0m       \u001b[1;31m# No tape is watching; skip to running the function.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1963\u001b[1;33m       return self._build_call_outputs(self._inference_function.call(\n\u001b[0m\u001b[0;32m   1964\u001b[0m           ctx, args, cancellation_manager=cancellation_manager))\n\u001b[0;32m   1965\u001b[0m     forward_backward = self._select_forward_and_backward_functions(\n",
      "\u001b[1;32m~\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\u001b[0m in \u001b[0;36mcall\u001b[1;34m(self, ctx, args, cancellation_manager)\u001b[0m\n\u001b[0;32m    589\u001b[0m       \u001b[1;32mwith\u001b[0m \u001b[0m_InterpolateFunctionError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    590\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mcancellation_manager\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 591\u001b[1;33m           outputs = execute.execute(\n\u001b[0m\u001b[0;32m    592\u001b[0m               \u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msignature\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mname\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    593\u001b[0m               \u001b[0mnum_outputs\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_num_outputs\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[1;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[0;32m     57\u001b[0m   \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     58\u001b[0m     \u001b[0mctx\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 59\u001b[1;33m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[0;32m     60\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[0;32m     61\u001b[0m   \u001b[1;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mUnimplementedError\u001b[0m:  Cast string to float is not supported\n\t [[node categorical_crossentropy/Cast (defined at <ipython-input-87-a716fff89f9e>:1) ]] [Op:__inference_train_function_2954]\n\nFunction call stack:\ntrain_function\n"
     ]
    }
   ],
   "source": [
    "history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=20, callbacks=[early_stop])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 97,
   "id": "95c0bf7e-ad46-4910-93c4-f1dcef79d5eb",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:788 train_step\n",
      "        loss = self.compiled_loss(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\compile_utils.py:201 __call__\n",
      "        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:141 __call__\n",
      "        losses = call_fn(y_true, y_pred)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:245 call  **\n",
      "        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:1665 categorical_crossentropy\n",
      "        return backend.categorical_crossentropy(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\backend.py:4839 categorical_crossentropy\n",
      "        target.shape.assert_is_compatible_with(output.shape)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1161 assert_is_compatible_with\n",
      "        raise ValueError(\"Shapes %s and %s are incompatible\" % (self, other))\n",
      "\n",
      "    ValueError: Shapes (None, 33) and (None, 3) are incompatible\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:788 train_step\n",
      "        loss = self.compiled_loss(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\compile_utils.py:201 __call__\n",
      "        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:141 __call__\n",
      "        losses = call_fn(y_true, y_pred)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:245 call  **\n",
      "        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:1665 categorical_crossentropy\n",
      "        return backend.categorical_crossentropy(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\backend.py:4839 categorical_crossentropy\n",
      "        target.shape.assert_is_compatible_with(output.shape)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1161 assert_is_compatible_with\n",
      "        raise ValueError(\"Shapes %s and %s are incompatible\" % (self, other))\n",
      "\n",
      "    ValueError: Shapes (None, 33) and (None, 3) are incompatible\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:788 train_step\n",
      "        loss = self.compiled_loss(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\compile_utils.py:201 __call__\n",
      "        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:141 __call__\n",
      "        losses = call_fn(y_true, y_pred)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:245 call  **\n",
      "        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:1665 categorical_crossentropy\n",
      "        return backend.categorical_crossentropy(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\backend.py:4839 categorical_crossentropy\n",
      "        target.shape.assert_is_compatible_with(output.shape)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1161 assert_is_compatible_with\n",
      "        raise ValueError(\"Shapes %s and %s are incompatible\" % (self, other))\n",
      "\n",
      "    ValueError: Shapes (None, 33) and (None, 3) are incompatible\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:788 train_step\n",
      "        loss = self.compiled_loss(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\compile_utils.py:201 __call__\n",
      "        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:141 __call__\n",
      "        losses = call_fn(y_true, y_pred)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:245 call  **\n",
      "        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:1665 categorical_crossentropy\n",
      "        return backend.categorical_crossentropy(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\backend.py:4839 categorical_crossentropy\n",
      "        target.shape.assert_is_compatible_with(output.shape)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1161 assert_is_compatible_with\n",
      "        raise ValueError(\"Shapes %s and %s are incompatible\" % (self, other))\n",
      "\n",
      "    ValueError: Shapes (None, 33) and (None, 3) are incompatible\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:788 train_step\n",
      "        loss = self.compiled_loss(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\compile_utils.py:201 __call__\n",
      "        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:141 __call__\n",
      "        losses = call_fn(y_true, y_pred)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:245 call  **\n",
      "        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:1665 categorical_crossentropy\n",
      "        return backend.categorical_crossentropy(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\backend.py:4839 categorical_crossentropy\n",
      "        target.shape.assert_is_compatible_with(output.shape)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1161 assert_is_compatible_with\n",
      "        raise ValueError(\"Shapes %s and %s are incompatible\" % (self, other))\n",
      "\n",
      "    ValueError: Shapes (None, 33) and (None, 3) are incompatible\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:788 train_step\n",
      "        loss = self.compiled_loss(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\compile_utils.py:201 __call__\n",
      "        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:141 __call__\n",
      "        losses = call_fn(y_true, y_pred)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:245 call  **\n",
      "        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:1665 categorical_crossentropy\n",
      "        return backend.categorical_crossentropy(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\backend.py:4839 categorical_crossentropy\n",
      "        target.shape.assert_is_compatible_with(output.shape)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1161 assert_is_compatible_with\n",
      "        raise ValueError(\"Shapes %s and %s are incompatible\" % (self, other))\n",
      "\n",
      "    ValueError: Shapes (None, 33) and (None, 3) are incompatible\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:788 train_step\n",
      "        loss = self.compiled_loss(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\compile_utils.py:201 __call__\n",
      "        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:141 __call__\n",
      "        losses = call_fn(y_true, y_pred)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:245 call  **\n",
      "        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:1665 categorical_crossentropy\n",
      "        return backend.categorical_crossentropy(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\backend.py:4839 categorical_crossentropy\n",
      "        target.shape.assert_is_compatible_with(output.shape)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1161 assert_is_compatible_with\n",
      "        raise ValueError(\"Shapes %s and %s are incompatible\" % (self, other))\n",
      "\n",
      "    ValueError: Shapes (None, 33) and (None, 3) are incompatible\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:788 train_step\n",
      "        loss = self.compiled_loss(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\compile_utils.py:201 __call__\n",
      "        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:141 __call__\n",
      "        losses = call_fn(y_true, y_pred)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:245 call  **\n",
      "        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:1665 categorical_crossentropy\n",
      "        return backend.categorical_crossentropy(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\backend.py:4839 categorical_crossentropy\n",
      "        target.shape.assert_is_compatible_with(output.shape)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1161 assert_is_compatible_with\n",
      "        raise ValueError(\"Shapes %s and %s are incompatible\" % (self, other))\n",
      "\n",
      "    ValueError: Shapes (None, 33) and (None, 3) are incompatible\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:788 train_step\n",
      "        loss = self.compiled_loss(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\compile_utils.py:201 __call__\n",
      "        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:141 __call__\n",
      "        losses = call_fn(y_true, y_pred)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:245 call  **\n",
      "        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:1665 categorical_crossentropy\n",
      "        return backend.categorical_crossentropy(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\backend.py:4839 categorical_crossentropy\n",
      "        target.shape.assert_is_compatible_with(output.shape)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1161 assert_is_compatible_with\n",
      "        raise ValueError(\"Shapes %s and %s are incompatible\" % (self, other))\n",
      "\n",
      "    ValueError: Shapes (5, 33) and (5, 3) are incompatible\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Baseline: nan% (nan%)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\training.py:788 train_step\n",
      "        loss = self.compiled_loss(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\engine\\compile_utils.py:201 __call__\n",
      "        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:141 __call__\n",
      "        losses = call_fn(y_true, y_pred)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:245 call  **\n",
      "        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\losses.py:1665 categorical_crossentropy\n",
      "        return backend.categorical_crossentropy(\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\n",
      "        return target(*args, **kwargs)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\keras\\backend.py:4839 categorical_crossentropy\n",
      "        target.shape.assert_is_compatible_with(output.shape)\n",
      "    C:\\Users\\Adam\\anaconda3\\envs\\dsi\\lib\\site-packages\\tensorflow\\python\\framework\\tensor_shape.py:1161 assert_is_compatible_with\n",
      "        raise ValueError(\"Shapes %s and %s are incompatible\" % (self, other))\n",
      "\n",
      "    ValueError: Shapes (5, 32) and (5, 3) are incompatible\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    }
   ],
   "source": [
    "# encoder = LabelEncoder()\n",
    "# encoder.fit(Y)\n",
    "# encoded_Y = encoder.transform(Y)\n",
    "# # convert integers to dummy variables (i.e. one hot encoded)\n",
    "# dummy_y = np_utils.to_categorical(encoded_Y)\n",
    " \n",
    "# define baseline model\n",
    "def baseline_model():\n",
    "    # create model\n",
    "    model = Sequential()\n",
    "    model.add(Dense(8, activation='relu'))\n",
    "    model.add(Dense(3, activation='softmax'))\n",
    "    # Compile model\n",
    "    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])\n",
    "    return model\n",
    " \n",
    "estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)\n",
    "kfold = KFold(n_splits=10, shuffle=True)\n",
    "results = cross_val_score(estimator, X, y, cv=kfold)\n",
    "print(\"Baseline: %.2f%% (%.2f%%)\" % (results.mean()*100, results.std()*100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "258a8b7f-0b75-4ea5-92e8-6a458e8e8655",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d45e64d6-d274-422d-a4d7-05446d3cc62d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fdab4eb5-131e-4fe3-ae8e-a2190f7b6654",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:dsi] *",
   "language": "python",
   "name": "conda-env-dsi-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
